### ISSUE TITLE
App UI is doesn't respond well to resized window

### ISSUE THREAD

**Issue by chrisp-miro** [zuev93/calculator_miro#1]
When resizing the browser window the calculator app UI doesn't resize elegantly with all the components:

![image](https://user-images.githubusercontent.com/108520540/212720297-3b69cff1-7a52-4155-93c5-206451d7ea1c.png)

**Comment by zuev93** [comment]
Adjusted the UI to better resize in case of high zoom level.
Also make it scrollable in case if it is required.
